name: Webhook Action
  # You may pin to the exact commit or the version.
  # uses: joelwmale/webhook-action@6f6298309b7aa21dc601d8c6271e0be055ce6f0e
uses: joelwmale/webhook-action@2.1.0
with:
  # The url to send the webhook event to
  url: 
  # Additional headers to send alongside the defaults
  headers: # optional
  # The data sent to the webhook
  body: # optional
  # Enables calling to known self-signed or invalid SSL certificates
  insecure: # optional
